### ISSUE TITLE
Atomic writes to file

### ISSUE THREAD

**Issue by tfiers** [tfiers/sharp#57]
Each FileTarget must first write to a temp file, then when done, copy it out to final dest.

This is to avoid Luigi's [atomic writes problem](https://luigi.readthedocs.io/en/stable/luigi_patterns.html#atomic-writes-problem)
(i.e. other workers thinking a task is complete when its output is still being written)

**Comment by tfiers** [comment]
Cause of this?

```
Traceback for DownsampleRawRecording(config_id=dev, file_ID=Rec(rat 2, day 1, D15))
Runtime error:
Traceback (most recent call last):
  File "/export/opt/anaconda2/envs/tomas/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/export/opt/anaconda2/envs/tomas/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
    task_gen = self.task.run()
  File "/mnt/nerfhf01/kloostermanwip/Tomas/code/sharp/sharp/tasks/base.py", line 45, in run
    self.work()
  File "/mnt/nerfhf01/kloostermanwip/Tomas/code/sharp/sharp/tasks/signal/downsample.py", line 57, in work
    self.output().write(Signal(signal_down, fs_new, "μV"))
  File "/mnt/nerfhf01/kloostermanwip/Tomas/code/sharp/sharp/data/files/numpy.py", line 57, in write
    dataset = f.create_dataset(self.KEY_SIG, data=signal.data)
  File "/export/opt/anaconda2/envs/tomas/lib/python3.7/site-packages/h5py/_hl/group.py", line 119, in create_dataset
    self[name] = dset
  File "/export/opt/anaconda2/envs/tomas/lib/python3.7/site-packages/h5py/_hl/group.py", line 287, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)
```
